
(function(){
 const messages={
  miss:{title:'Kalau kamu lagi kangen aku…',text:'Andai aku bisa, sekarang aku sudah ada di sampingmu. Untuk sementara, anggap pesan ini sebagai peluk kecil dariku. Jarak mungkin bikin kita nggak bisa bertemu kapan saja, tapi kamu tetap punya tempat di hatiku. Aku juga menantikan saat kita bisa bertemu lagi. 🤍'},
  sad:{title:'Kalau hari ini terasa berat…',text:'Sayang, kamu nggak harus kuat setiap saat. Kamu boleh capek, boleh menangis, boleh istirahat dan nggak melakukan apa-apa sebentar. Hari yang sulit bukan berarti kamu gagal. Ambil waktu untuk dirimu, ya. Aku bangga kamu sudah melewati sejauh ini.'},
  doubt:{title:'Kalau kamu lupa betapa berharganya dirimu…',text:'Aku sayang kamu bukan karena kamu harus selalu ceria, selalu sempurna, atau selalu punya jawaban. Aku sayang kamu sebagai dirimu sendiri—termasuk bagian dirimu yang sedang lelah dan belum baik-baik saja. Kamu pantas diperlakukan dengan lembut, terutama oleh dirimu sendiri. 🌷'},
  sleep:{title:'Untuk malam yang terasa panjang…',text:'Letakkan dulu semua yang bisa menunggu sampai besok. Longgarkan bahumu, tarik napas perlahan, lalu hembuskan. Kamu nggak perlu menyelesaikan semua hal malam ini. Semoga kamu merasa aman, hangat, dan bisa beristirahat. Selamat tidur, sayang. ☾'},
  fight:{title:'Kalau kita sedang nggak baik-baik saja…',text:'Kalau ada yang menyakitimu, aku ingin mendengarkannya dengan sungguh-sungguh. Kita nggak harus langsung menyelesaikan semuanya saat emosi masih tinggi. Kita bisa berhenti sebentar, lalu bicara lagi dengan lebih tenang dan saling menghargai. Perasaanmu penting buat aku. 💌'},
  hug:{title:'Sini, aku peluk dulu…',text:'Nggak perlu menjelaskan apa-apa kalau kamu belum siap. Bayangkan aku merangkulmu, membiarkanmu bersandar sebentar, dan mengingatkanmu bahwa kamu nggak harus melewati hari ini dengan sempurna. Satu napas dulu, ya. 🫂'}
 };
 const letter=document.getElementById('comfortLetter');
 document.querySelectorAll('[data-comfort]').forEach(btn=>btn.addEventListener('click',()=>{const m=messages[btn.dataset.comfort];if(!m)return;document.getElementById('comfortLetterTitle').textContent=m.title;document.getElementById('comfortLetterText').textContent=m.text;letter.classList.add('show');letter.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'});if(typeof window.romanticRecordAnswer==='function'){try{window.romanticRecordAnswer('mood_letter',m.title,'Pesan dibuka');}catch(e){}}}));
 document.getElementById('comfortClose').addEventListener('click',()=>letter.classList.remove('show'));
 const overlay=document.getElementById('comfortAffection');function closeHug(){overlay.classList.remove('show')}
 document.getElementById('comfortHug').addEventListener('click',()=>overlay.classList.add('show'));document.getElementById('closeComfortAffection').addEventListener('click',closeHug);overlay.addEventListener('click',e=>{if(e.target===overlay)closeHug()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeHug()});
 const input=document.getElementById('personalVoice'),player=document.getElementById('personalVoicePlayer'),status=document.getElementById('voiceStatus');let objectUrl='';
 input.addEventListener('change',()=>{const file=input.files&&input.files[0];if(!file)return;if(!file.type.startsWith('audio/')){status.textContent='Pilih file audio yang valid ya.';return}if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(file);player.src=objectUrl;player.hidden=false;status.textContent='Siap diputar: '+file.name+' · hanya di perangkat ini.';});
 const bedtime=document.getElementById('bedtimeToggle'),section=document.getElementById('ruang-nyaman');bedtime.addEventListener('click',()=>{const active=section.classList.toggle('bedtime-mode');bedtime.textContent=active?'Kembali ke tampilan biasa ♡':'Masuk mode sebelum tidur ☾';document.body.style.overflow=active?'hidden':'';if(active)section.scrollTop=0;});
})();
